name: Deploy App

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME_BACKEND: yur0n/yes-backend
  IMAGE_NAME_FRONTEND: yur0n/yes-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push backend
        run: |
          docker build -t $IMAGE_NAME_BACKEND:latest ./backend
          docker push $IMAGE_NAME_BACKEND:latest

      - name: Build & Push frontend
        run: |
          docker build -t $IMAGE_NAME_FRONTEND:latest ./frontend
          docker push $IMAGE_NAME_FRONTEND:latest

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd main
            docker compose pull
            docker compose up -d
